version: "3.7"

services:
    electrum:
        build: .
        ports:
            - 127.0.0.1:7000:7000
        environment:
            - ELECTRUM_USER=steve
            - ELECTRUM_PASSWORD=changeme
            - ELECTRUM_NETWORK=testnet
            - ELECTRUM_VERSION=4.2.1
        container_name: electrum
        image: zambaizo/electrum-daemon
        volumes:
            - ../electrum:/data
